spring:
  profiles:
    include:
      - native

#  security:
#    user:
#      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: beans,mappings,health,info