//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.24 at 12:49:43 PM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.core.sw.bps.com/")
package com.vosouq.paymentgateway.mellat.webservice.ipg.gen2;
