# Jalali Date Constants
from app.core.services.sort_type import SortType

PERSIAN_LOCALE = 'fa_IR'

rules_min_val = 0
rules_max_val = 999
score_deliminator = ':'

# scoring default values
NOT_PROCESSED_SCORE = -1

# Scoring Distribution Keys
SCORE_DISTRIBUTION_SEPARATOR = '_to_'
COUNT_KEY = 'cnt'

# general average parameters
MINUS_ONE = -1
ZERO = 0
ONE = 1
SIX = 6
TWELVE = 12
THIRTY = 30
ONE_HUNDRED = 100
NORMALIZATION_MAX_SCORE = 1000
# GENERAL_AVG_DEAL_AMOUNT = 50000000
GENERAL_AVG_DEAL_AMOUNT = 5000000000
# GENERAL_AVG_BALANCE = 100000000
GENERAL_AVG_DELAY_DAYS = 2
ALL_USERS_AVERAGE_DEAL_AMOUNT = 10000000
ALL_USERS_AVERAGE_UNFIXED_RETURNED_CHEQUES_AMOUNT = 500000000
ALL_USERS_AVERAGE_MONTHLY_INSTALLMENT_AMOUNT = 25000000
ALL_USERS_AVERAGE_PRINCIPAL_INTEREST_AMOUNT = 700000000

# Models fields' names
USER_ID = 'user_id'
PARENT = 'parent'
CODE = 'code'
SCORE = 'score'
MAX = 'max'
IMPACT_PERCENT = 'impact_percent'
TOTAL_DELAY_DAYS = 'total_delay_days'
RECOMMENDED_TO_OTHERS_COUNT = 'recommended_to_others_count'
MEMBERSHIP_DATE = 'membership_date'
YEARS = 'years'
MONTHS = 'months'
DAYS = 'days'
UNDUE_TRADES_COUNT = 'undue_trades_count'
PAST_DUE_TRADES_COUNT = 'past_due_trades_count'
ARREAR_TRADES_COUNT = 'arrear_trades_count'
SCORE_DATE = 'score_date'
RULE_MASTER_CODE = 'rule_master_code'
RULE_CODES = 'rule_codes'

# scoring dict keys
IDENTITIES_SCORE = 'IDENTITIES_SCORE'
HISTORIES_SCORE = 'HISTORIES_SCORE'
VOLUMES_SCORE = 'VOLUMES_SCORE'
TIMELINESS_SCORE = 'TIMELINESS_SCORE'

# Redis masters set keys
RDS_PERCENT = 'percent'
RDS_SCORE = 'score'

IDENTITIES = 'I'
SET_RULES_IDENTITIES_MASTER = 'set_rules_identities_master'

HISTORIES = 'H'
SET_RULES_HISTORIES_MASTER = 'set_rules_histories_master'

VOLUMES = 'V'
SET_RULES_VOLUMES_MASTER = 'set_rules_volumes_master'

TIMELINESS = 'T'
SET_RULES_TIMELINESS_MASTER = 'set_rules_timeliness_master'

# identities set keys
I1_RULES_PROFILE_HAS_KYCS = 'I1'
SET_RULES_PROFILE_HAS_KYCS = 'set_rules_profile_has_kycs'

I2_RULES_PROFILE_MILITARY_SERVICE_STATUS = 'I2'
SET_RULES_PROFILE_MILITARY_SERVICE_STATUS = 'set_rules_profile_military_service_status'

I3_RULES_PROFILE_SIM_CARD_OWNERSHIPS = 'I3'
SET_RULES_PROFILE_SIM_CARD_OWNERSHIPS = 'set_rules_profile_sim_card_ownerships'

I4_RULES_PROFILE_ADDRESS_VERIFICATIONS = 'I4'
SET_RULES_PROFILE_ADDRESS_VERIFICATIONS = 'set_rules_profile_address_verifications'

# histories set keys
H5_RULES_PROFILE_MEMBERSHIP_DAYS_COUNTS = 'H5'
SET_RULES_PROFILE_MEMBERSHIP_DAYS_COUNTS = 'set_rules_profile_membership_days_counts'

H6_RULES_DONE_TIMELY_TRADES_OF_LAST_3_MONTHS = 'H6'
SET_RULES_DONE_TIMELY_TRADES_OF_LAST_3_MONTHS = 'set_rules_done_timely_trades_of_last_3_months'

H7_RULES_DONE_TIMELY_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'H7'
SET_RULES_DONE_TIMELY_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'set_rules_done_timely_trades_between_last_3_to_12_months'

H8_RULES_PROFILE_RECOMMENDED_TO_OTHERS_COUNTS = 'H8'
SET_RULES_PROFILE_RECOMMENDED_TO_OTHERS_COUNTS = 'set_rules_profile_recommended_to_others_counts'

H9_RULES_PROFILE_STAR_COUNTS_AVGS = 'H9'
SET_RULES_PROFILE_STAR_COUNTS_AVGS = 'set_rules_profile_star_counts_avgs'

H10_RULES_UNDONE_UNDUE_TRADES_COUNTS = 'H10'
SET_RULES_UNDONE_UNDUE_TRADES_COUNTS = 'set_rules_undone_undue_trades_counts'

H11_RULES_LOAN_TOTAL_COUNTS = 'H11'
SET_RULES_LOAN_TOTAL_COUNTS = 'set_rules_loan_total_counts'

# volumes set keys
V12_RULES_DONE_TRADES_AVERAGE_TOTAL_BALANCE_RATIOS = 'V12'
SET_RULES_DONE_TRADES_AVERAGE_TOTAL_BALANCE_RATIOS = 'set_rules_done_trades_total_balance_ratios'

V13_RULES_UNDONE_PAST_DUE_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'V13'
SET_RULES_UNDONE_PAST_DUE_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'set_rules_undone_past_due_trades_total_balance_of_last_year_ratios'

V14_RULES_UNDONE_ARREAR_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'V14'
SET_RULES_UNDONE_ARREAR_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'set_rules_undone_arrear_trades_total_balance_of_last_year_ratios'

V15_RULES_UNDONE_UNDUE_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'V15'
SET_RULES_UNDONE_UNDUE_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'set_rules_undone_undue_trades_total_balance_of_last_year_ratios'

V16_RULES_LOAN_MONTHLY_INSTALLMENTS_TOTAL_BALANCE_RATIOS = 'V16'
SET_RULES_LOAN_MONTHLY_INSTALLMENTS_TOTAL_BALANCE_RATIOS = 'set_rules_loan_monthly_installments_total_balance_ratios'

V17_RULES_CHEQUE_UNFIXED_RETURNED_TOTAL_BALANCE_RATIOS = 'V17'
SET_RULES_CHEQUE_UNFIXED_RETURNED_TOTAL_BALANCE_RATIOS = 'set_rules_cheque_unfixed_returned_total_balance_ratios'

V18_RULES_LOAN_OVERDUE_TOTAL_BALANCE_RATIOS = 'V18'
SET_RULES_LOAN_OVERDUE_TOTAL_BALANCE_RATIOS = 'set_rules_loan_overdue_total_balance_ratios'

V19_RULES_LOAN_PAST_DUE_TOTAL_BALANCE_RATIOS = 'V19'
SET_RULES_LOAN_PAST_DUE_TOTAL_BALANCE_RATIOS = 'set_rules_loan_past_due_total_balance_ratios'

V20_RULES_LOAN_ARREAR_TOTAL_BALANCE_RATIOS = 'V20'
SET_RULES_LOAN_ARREAR_TOTAL_BALANCE_RATIOS = 'set_rules_loan_arrear_total_balance_ratios'

V21_RULES_LOAN_SUSPICIOUS_TOTAL_BALANCE_RATIOS = 'V21'
SET_RULES_LOAN_SUSPICIOUS_TOTAL_BALANCE_RATIOS = 'set_rules_loan_suspicious_total_balance_ratios'

# timeliness set keys
T22_RULES_DONE_PAST_DUE_TRADES_OF_LAST_3_MONTHS = 'T22'
SET_RULES_DONE_PAST_DUE_TRADES_OF_LAST_3_MONTHS = 'set_rules_done_past_due_trades_of_last_3_months'

T23_RULES_DONE_PAST_DUE_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'T23'
SET_RULES_DONE_PAST_DUE_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'set_rules_done_past_due_trades_between_last_3_to_12_months'

T24_RULES_DONE_ARREAR_TRADES_OF_LAST_3_MONTHS = 'T24'
SET_RULES_DONE_ARREAR_TRADES_OF_LAST_3_MONTHS = 'set_rules_done_arrear_trades_of_last_3_months'

T25_RULES_DONE_ARREAR_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'T25'
SET_RULES_DONE_ARREAR_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'set_rules_done_arrear_trades_between_last_3_to_12_months'

T26_RULES_UNDONE_PAST_DUE_TRADES_COUNTS = 'T26'
SET_RULES_UNDONE_PAST_DUE_TRADES_COUNTS = 'set_rules_undone_past_due_trades_counts'

T27_RULES_UNDONE_ARREAR_TRADES_COUNTS = 'T27'
SET_RULES_UNDONE_ARREAR_TRADES_COUNTS = 'set_rules_undone_arrear_trades_counts'

T28_RULES_DONE_TRADES_AVERAGE_DELAY_DAYS = 'T28'
SET_RULES_DONE_TRADES_AVERAGE_DELAY_DAYS = 'set_rules_trades_done_average_delay_days'

T29_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_OF_LAST_3_MONTHS = 'T29'
SET_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_OF_LAST_3_MONTHS = 'set_rules_cheque_unfixed_returned_count_of_last_3_months'

T30_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_BETWEEN_LAST_3_TO_12_MONTHS = 'T30'
SET_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_BETWEEN_LAST_3_TO_12_MONTHS = 'set_rules_cheque_unfixed_returned_count_between_last_3_to_12_months'

T31_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_OF_MORE_12_MONTHS = 'T31'
SET_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_OF_MORE_12_MONTHS = 'set_rules_cheque_unfixed_returned_count_of_more_12_months'

T32_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_OF_LAST_5_YEARS = 'T32'
SET_RULES_CHEQUE_UNFIXED_RETURNED_COUNT_OF_LAST_5_YEARS = 'set_rules_cheque_unfixed_returned_count_of_last_5_years'

T33_RULES_LOAN_PAST_DUE_TOTAL_COUNTS = 'T33'
SET_RULES_LOAN_PAST_DUE_TOTAL_COUNTS = 'set_rules_loan_past_due_total_counts'

T34_RULES_LOAN_ARREAR_TOTAL_COUNTS = 'T34'
SET_RULES_LOAN_ARREAR_TOTAL_COUNTS = 'set_rules_loan_arrear_total_counts'

T35_RULES_LOAN_SUSPICIOUS_TOTAL_COUNTS = 'T35'
SET_RULES_LOAN_SUSPICIOUS_TOTAL_COUNTS = 'set_rules_loan_suspicious_total_counts'

# SCORE CODES
SCORE_CODE_RULES_UNDONE_PAST_DUE_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'V1303N10'
SCORE_CODE_RULES_UNDONE_ARREAR_TRADES_TOTAL_BALANCE_OF_LAST_YEAR_RATIOS = 'V1403N10'

# BUSINESS CONVENTION
PAGE_SIZE_DEFAULT = 25
PAGE_NO_DEFAULT = 1
SORT_TYPE_DEFAULT = False
