eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.12.5:8000/registry/eureka
    instance:
        prefer-ip-address: true
logging:
    level:
        com:
            vosouq: debug
        org: info
        root: info
spring:
    application:
        name: contract-local
    datasource:
        driver-class-name: org.postgresql.Driver
        password: password
        url: jdbc:postgresql://localhost:5432/contract
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                connection:
                    CharSet: UTF-8
                    characterEncoding: UTF-8
                    useUnicode: UTF-8
        show-sql: true
server:
    port: 8099
