# The Actuator configuration.
scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    # List of Eureka service discovery configurations.
    eureka_sd_configs:
    # The URL to connect to the Eureka server.
      - server: http://172.17.0.1:8761/eureka
        refresh_interval: 10s