
package com.vosouq.kyc.faranam;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InquirySoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InquirySoap {


    /**
     * 
     * @param chequeSeriChar
     * @param password
     * @param returnDate
     * @param supplyType
     * @param chequeSerial
     * @param supplyDate
     * @param userName
     * @param chequeSeriNumber
     * @param branch
     * @param account
     * @return
     *     returns com.vosouq.contract.faranam.AddTamChequeModel
     */
    @WebMethod(operationName = "AddCheqeTam", action = "http://tempuri.org/AddCheqeTam")
    @WebResult(name = "AddCheqeTamResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddCheqeTam", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.AddCheqeTam")
    @ResponseWrapper(localName = "AddCheqeTamResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.AddCheqeTamResponse")
    public AddTamChequeModel addCheqeTam(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "branch", targetNamespace = "http://tempuri.org/")
        String branch,
        @WebParam(name = "chequeSerial", targetNamespace = "http://tempuri.org/")
        String chequeSerial,
        @WebParam(name = "chequeSeriChar", targetNamespace = "http://tempuri.org/")
        String chequeSeriChar,
        @WebParam(name = "chequeSeriNumber", targetNamespace = "http://tempuri.org/")
        String chequeSeriNumber,
        @WebParam(name = "returnDate", targetNamespace = "http://tempuri.org/")
        String returnDate,
        @WebParam(name = "supplyDate", targetNamespace = "http://tempuri.org/")
        String supplyDate,
        @WebParam(name = "supplyType", targetNamespace = "http://tempuri.org/")
        String supplyType);

    /**
     * 
     * @param nationalCode
     * @param password
     * @param userName
     * @return
     *     returns com.vosouq.contract.faranam.BankCustomerModel
     */
    @WebMethod(operationName = "InquiryFromBankCustomers", action = "http://tempuri.org/InquiryFromBankCustomers")
    @WebResult(name = "InquiryFromBankCustomersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InquiryFromBankCustomers", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromBankCustomers")
    @ResponseWrapper(localName = "InquiryFromBankCustomersResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromBankCustomersResponse")
    public BankCustomerModel inquiryFromBankCustomers(
        @WebParam(name = "nationalCode", targetNamespace = "http://tempuri.org/")
        String nationalCode,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param nationalCode
     * @param password
     * @param userName
     * @param birthDate
     * @return
     *     returns com.vosouq.contract.faranam.NOCRPersonModel
     */
    @WebMethod(operationName = "InquiryFromNOCR", action = "http://tempuri.org/InquiryFromNOCR")
    @WebResult(name = "InquiryFromNOCRResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InquiryFromNOCR", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromNOCR")
    @ResponseWrapper(localName = "InquiryFromNOCRResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromNOCRResponse")
    public NOCRPersonModel inquiryFromNOCR(
        @WebParam(name = "nationalCode", targetNamespace = "http://tempuri.org/")
        String nationalCode,
        @WebParam(name = "birthDate", targetNamespace = "http://tempuri.org/")
        String birthDate,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param nationalCode
     * @param password
     * @param userName
     * @param birthDate
     * @return
     *     returns com.vosouq.contract.faranam.NOCRPersonModel
     */
    @WebMethod(operationName = "InquiryFromNOCRmellatEstelamDB", action = "http://tempuri.org/InquiryFromNOCRmellatEstelamDB")
    @WebResult(name = "InquiryFromNOCRmellatEstelamDBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InquiryFromNOCRmellatEstelamDB", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromNOCRmellatEstelamDB")
    @ResponseWrapper(localName = "InquiryFromNOCRmellatEstelamDBResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromNOCRmellatEstelamDBResponse")
    public NOCRPersonModel inquiryFromNOCRmellatEstelamDB(
        @WebParam(name = "nationalCode", targetNamespace = "http://tempuri.org/")
        String nationalCode,
        @WebParam(name = "birthDate", targetNamespace = "http://tempuri.org/")
        String birthDate,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param nationalId
     * @param userName
     * @return
     *     returns com.vosouq.contract.faranam.ILENCPersonModel
     */
    @WebMethod(operationName = "InquiryFromILENCByNationalId", action = "http://tempuri.org/InquiryFromILENCByNationalId")
    @WebResult(name = "InquiryFromILENCByNationalIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InquiryFromILENCByNationalId", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromILENCByNationalId")
    @ResponseWrapper(localName = "InquiryFromILENCByNationalIdResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromILENCByNationalIdResponse")
    public ILENCPersonModel inquiryFromILENCByNationalId(
        @WebParam(name = "nationalId", targetNamespace = "http://tempuri.org/")
        String nationalId,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param legalName
     * @param password
     * @param userName
     * @return
     *     returns com.vosouq.contract.faranam.ILENCPersonModel
     */
    @WebMethod(operationName = "InquiryFromILENCByLegalName", action = "http://tempuri.org/InquiryFromILENCByLegalName")
    @WebResult(name = "InquiryFromILENCByLegalNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InquiryFromILENCByLegalName", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromILENCByLegalName")
    @ResponseWrapper(localName = "InquiryFromILENCByLegalNameResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.InquiryFromILENCByLegalNameResponse")
    public ILENCPersonModel inquiryFromILENCByLegalName(
        @WebParam(name = "legalName", targetNamespace = "http://tempuri.org/")
        String legalName,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param dtSbt
     * @param password
     * @param noSbt
     * @param cdSbt
     * @param cstmrTp
     * @param userName
     * @param idNo
     * @return
     *     returns com.vosouq.contract.faranam.ChqResponse
     */
    @WebMethod(operationName = "EstelamChequeDetails", action = "http://tempuri.org/EstelamChequeDetails")
    @WebResult(name = "EstelamChequeDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EstelamChequeDetails", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.EstelamChequeDetails")
    @ResponseWrapper(localName = "EstelamChequeDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.EstelamChequeDetailsResponse")
    public ChqResponse estelamChequeDetails(
        @WebParam(name = "cstmrTp", targetNamespace = "http://tempuri.org/")
        short cstmrTp,
        @WebParam(name = "idNo", targetNamespace = "http://tempuri.org/")
        String idNo,
        @WebParam(name = "dtSbt", targetNamespace = "http://tempuri.org/")
        String dtSbt,
        @WebParam(name = "noSbt", targetNamespace = "http://tempuri.org/")
        String noSbt,
        @WebParam(name = "cdSbt", targetNamespace = "http://tempuri.org/")
        String cdSbt,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param dtSbt
     * @param password
     * @param noSbt
     * @param cdSbt
     * @param cstmrTp
     * @param userName
     * @param idNo
     * @return
     *     returns com.vosouq.contract.faranam.TasResponse
     */
    @WebMethod(operationName = "EstlmTasDetails", action = "http://tempuri.org/EstlmTasDetails")
    @WebResult(name = "EstlmTasDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EstlmTasDetails", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.EstlmTasDetails")
    @ResponseWrapper(localName = "EstlmTasDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.EstlmTasDetailsResponse")
    public TasResponse estlmTasDetails(
        @WebParam(name = "cstmrTp", targetNamespace = "http://tempuri.org/")
        short cstmrTp,
        @WebParam(name = "idNo", targetNamespace = "http://tempuri.org/")
        String idNo,
        @WebParam(name = "dtSbt", targetNamespace = "http://tempuri.org/")
        String dtSbt,
        @WebParam(name = "noSbt", targetNamespace = "http://tempuri.org/")
        String noSbt,
        @WebParam(name = "cdSbt", targetNamespace = "http://tempuri.org/")
        String cdSbt,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param postcode
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.TelephoneNumbers
     */
    @WebMethod(operationName = "GetTelephonesByPostcode", action = "http://tempuri.org/GetTelephonesByPostcode")
    @WebResult(name = "GetTelephonesByPostcodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTelephonesByPostcode", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetTelephonesByPostcode")
    @ResponseWrapper(localName = "GetTelephonesByPostcodeResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetTelephonesByPostcodeResponse")
    public TelephoneNumbers getTelephonesByPostcode(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "postcode", targetNamespace = "http://tempuri.org/")
        String postcode);

    /**
     * 
     * @param password
     * @param preNo
     * @param phoneNo
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.IranStandardAddress
     */
    @WebMethod(operationName = "GetAddressByTelephone", action = "http://tempuri.org/GetAddressByTelephone")
    @WebResult(name = "GetAddressByTelephoneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAddressByTelephone", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressByTelephone")
    @ResponseWrapper(localName = "GetAddressByTelephoneResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressByTelephoneResponse")
    public IranStandardAddress getAddressByTelephone(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "preNo", targetNamespace = "http://tempuri.org/")
        int preNo,
        @WebParam(name = "phoneNo", targetNamespace = "http://tempuri.org/")
        int phoneNo);

    /**
     * 
     * @param password
     * @param preNo
     * @param phoneNo
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.Postcode
     */
    @WebMethod(operationName = "GetPostcodeByTelephone", action = "http://tempuri.org/GetPostcodeByTelephone")
    @WebResult(name = "GetPostcodeByTelephoneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPostcodeByTelephone", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetPostcodeByTelephone")
    @ResponseWrapper(localName = "GetPostcodeByTelephoneResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetPostcodeByTelephoneResponse")
    public Postcode getPostcodeByTelephone(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "preNo", targetNamespace = "http://tempuri.org/")
        int preNo,
        @WebParam(name = "phoneNo", targetNamespace = "http://tempuri.org/")
        int phoneNo);

    /**
     * 
     * @param password
     * @param postcode
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.IranStandardAddress
     */
    @WebMethod(operationName = "GetAddressByPostcode", action = "http://tempuri.org/GetAddressByPostcode")
    @WebResult(name = "GetAddressByPostcodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAddressByPostcode", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressByPostcode")
    @ResponseWrapper(localName = "GetAddressByPostcodeResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressByPostcodeResponse")
    public IranStandardAddress getAddressByPostcode(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "postcode", targetNamespace = "http://tempuri.org/")
        String postcode);

    /**
     * 
     * @param password
     * @param preNo
     * @param phoneNo
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.IranStandardAddress
     */
    @WebMethod(operationName = "GetAddressAndPostcodeByTelephone", action = "http://tempuri.org/GetAddressAndPostcodeByTelephone")
    @WebResult(name = "GetAddressAndPostcodeByTelephoneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAddressAndPostcodeByTelephone", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressAndPostcodeByTelephone")
    @ResponseWrapper(localName = "GetAddressAndPostcodeByTelephoneResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressAndPostcodeByTelephoneResponse")
    public IranStandardAddress getAddressAndPostcodeByTelephone(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "preNo", targetNamespace = "http://tempuri.org/")
        int preNo,
        @WebParam(name = "phoneNo", targetNamespace = "http://tempuri.org/")
        int phoneNo);

    /**
     * 
     * @param password
     * @param postcode
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.IranStandardAddressAndTelephones
     */
    @WebMethod(operationName = "GetAddressAndTelephoneByPostcode", action = "http://tempuri.org/GetAddressAndTelephoneByPostcode")
    @WebResult(name = "GetAddressAndTelephoneByPostcodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAddressAndTelephoneByPostcode", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressAndTelephoneByPostcode")
    @ResponseWrapper(localName = "GetAddressAndTelephoneByPostcodeResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetAddressAndTelephoneByPostcodeResponse")
    public IranStandardAddressAndTelephones getAddressAndTelephoneByPostcode(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "postcode", targetNamespace = "http://tempuri.org/")
        String postcode);

    /**
     * 
     * @param password
     * @param nationalCode
     * @param serial
     * @param seri
     * @param birthDate
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.NocrModel
     */
    @WebMethod(operationName = "NocrImageInquiry", action = "http://tempuri.org/NocrImageInquiry")
    @WebResult(name = "NocrImageInquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NocrImageInquiry", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImageInquiry")
    @ResponseWrapper(localName = "NocrImageInquiryResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImageInquiryResponse")
    public NocrModel nocrImageInquiry(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "nationalCode", targetNamespace = "http://tempuri.org/")
        long nationalCode,
        @WebParam(name = "birthDate", targetNamespace = "http://tempuri.org/")
        int birthDate,
        @WebParam(name = "seri", targetNamespace = "http://tempuri.org/")
        String seri,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param password
     * @param nationalCode
     * @param serial
     * @param seri
     * @param birthDate
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.NocrModel
     */
    @WebMethod(operationName = "NocrImageInquiry_test", action = "http://tempuri.org/NocrImageInquiry_test")
    @WebResult(name = "NocrImageInquiry_testResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NocrImageInquiry_test", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImageInquiryTest")
    @ResponseWrapper(localName = "NocrImageInquiry_testResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImageInquiryTestResponse")
    public NocrModel nocrImageInquiryTest(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "nationalCode", targetNamespace = "http://tempuri.org/")
        long nationalCode,
        @WebParam(name = "birthDate", targetNamespace = "http://tempuri.org/")
        int birthDate,
        @WebParam(name = "seri", targetNamespace = "http://tempuri.org/")
        String seri,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param password
     * @param nationalCode
     * @param serial
     * @param birthDate
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.NocrModel
     */
    @WebMethod(operationName = "NocrImageInquiryNew", action = "http://tempuri.org/NocrImageInquiryNew")
    @WebResult(name = "NocrImageInquiryNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NocrImageInquiryNew", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImageInquiryNew")
    @ResponseWrapper(localName = "NocrImageInquiryNewResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImageInquiryNewResponse")
    public NocrModel nocrImageInquiryNew(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "nationalCode", targetNamespace = "http://tempuri.org/")
        long nationalCode,
        @WebParam(name = "birthDate", targetNamespace = "http://tempuri.org/")
        int birthDate,
        @WebParam(name = "serial", targetNamespace = "http://tempuri.org/")
        String serial);

    /**
     * 
     * @param password
     * @param nationalCode
     * @param serialId
     * @param numericPartSeri
     * @param alphaPartSeri
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.NocrModel
     */
    @WebMethod(operationName = "NocrImage6Inquiry", action = "http://tempuri.org/NocrImage6Inquiry")
    @WebResult(name = "NocrImage6InquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NocrImage6Inquiry", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImage6Inquiry")
    @ResponseWrapper(localName = "NocrImage6InquiryResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrImage6InquiryResponse")
    public NocrModel nocrImage6Inquiry(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "nationalCode", targetNamespace = "http://tempuri.org/")
        long nationalCode,
        @WebParam(name = "numericPartSeri", targetNamespace = "http://tempuri.org/")
        String numericPartSeri,
        @WebParam(name = "alphaPartSeri", targetNamespace = "http://tempuri.org/")
        String alphaPartSeri,
        @WebParam(name = "serialId", targetNamespace = "http://tempuri.org/")
        String serialId);

    /**
     * 
     * @param request
     * @param password
     * @param username
     * @return
     *     returns com.vosouq.contract.faranam.EstelamResult3TModel
     */
    @WebMethod(operationName = "NocrGetEstelam3T", action = "http://tempuri.org/NocrGetEstelam3T")
    @WebResult(name = "NocrGetEstelam3TResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NocrGetEstelam3T", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrGetEstelam3T")
    @ResponseWrapper(localName = "NocrGetEstelam3TResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.NocrGetEstelam3TResponse")
    public EstelamResult3TModel nocrGetEstelam3T(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        Estelam3TRequest request);

    /**
     * 
     * @param dtSbt
     * @param password
     * @param nationalId
     * @param noSbt
     * @param cdSbt
     * @param userName
     * @return
     *     returns com.vosouq.contract.faranam.TasResponse
     */
    @WebMethod(operationName = "EstlmEtbLegal", action = "http://tempuri.org/EstlmEtbLegal")
    @WebResult(name = "EstlmEtbLegalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EstlmEtbLegal", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.EstlmEtbLegal")
    @ResponseWrapper(localName = "EstlmEtbLegalResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.EstlmEtbLegalResponse")
    public TasResponse estlmEtbLegal(
        @WebParam(name = "NationalId", targetNamespace = "http://tempuri.org/")
        String nationalId,
        @WebParam(name = "NoSbt", targetNamespace = "http://tempuri.org/")
        String noSbt,
        @WebParam(name = "DTSbt", targetNamespace = "http://tempuri.org/")
        String dtSbt,
        @WebParam(name = "CDSbt", targetNamespace = "http://tempuri.org/")
        String cdSbt,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param cstmrShenase
     * @param cstmrName
     * @param estlmId
     * @param userName
     * @param cstmrType
     * @param cstmrLName
     * @return
     *     returns com.vosouq.contract.faranam.EstelamAsliResponse
     */
    @WebMethod(operationName = "SamatTasHilatAsli", action = "http://tempuri.org/SamatTasHilatAsli")
    @WebResult(name = "SamatTasHilatAsliResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SamatTasHilatAsli", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.SamatTasHilatAsli")
    @ResponseWrapper(localName = "SamatTasHilatAsliResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.SamatTasHilatAsliResponse")
    public EstelamAsliResponse samatTasHilatAsli(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "estlmId", targetNamespace = "http://tempuri.org/")
        String estlmId,
        @WebParam(name = "cstmrType", targetNamespace = "http://tempuri.org/")
        String cstmrType,
        @WebParam(name = "cstmrShenase", targetNamespace = "http://tempuri.org/")
        String cstmrShenase,
        @WebParam(name = "cstmrName", targetNamespace = "http://tempuri.org/")
        String cstmrName,
        @WebParam(name = "cstmrLName", targetNamespace = "http://tempuri.org/")
        String cstmrLName);

    /**
     * 
     * @param password
     * @param nationalNo
     * @param userName
     * @return
     *     returns com.vosouq.contract.faranam.BARres
     */
    @WebMethod(operationName = "GetBlockAccountReport", action = "http://tempuri.org/GetBlockAccountReport")
    @WebResult(name = "GetBlockAccountReportResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBlockAccountReport", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetBlockAccountReport")
    @ResponseWrapper(localName = "GetBlockAccountReportResponse", targetNamespace = "http://tempuri.org/", className = "com.vosouq.contract.faranam.GetBlockAccountReportResponse")
    public BARres getBlockAccountReport(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "NationalNo", targetNamespace = "http://tempuri.org/")
        String nationalNo);

}
