logging:
  level:
    org.springframework.security: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        excluede: "env, beans, shutdown"